[package]
name = "pocus"
version = "0.1.0"
authors = ["Joachim Enggaard Nebel"]
edition = "2021"
license = "BSD-2-Clause"
description = "Chess GUI with a focus on engine testing tournaments"


[dependencies]
chess = "3.2.0"
dioxus = "0.3.2"
dioxus-desktop = "0.3.0"