[package]
name = "pocus"
version = "0.1.0"
authors = ["Joachim Enggaard Nebel"]
edition = "2021"
license = "BSD-2-Clause"
description = "Chess GUI with a focus on engine testing tournaments"


[dependencies]
chess = "3.2.0"